[features]
seeds = false
[programs.localnet]
solana_leetdroid = "E3s8VLFoVor6k7oXC6yrsCpgvJoky26zPceeF8eGBPtD"

[programs.devnet]
solana_leetdroid = "E3s8VLFoVor6k7oXC6yrsCpgvJoky26zPceeF8eGBPtD"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/thefunnyintrovert/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
